/**
 * Synapse daemon — single long-lived MCP server, multi-client.
 *
 * Each connecting shim presents:
 *   - Authorization: Bearer <token>           (auth, from ~/.claude/synapse/daemon.json)
 *   - X-Synapse-Label: <label>                (identifies client class — code/desktop/etc)
 *   - X-Synapse-Identity-Token: <client-uuid> (sticky identity, generated by the shim)
 *
 * The daemon binds <label, identityToken> to a single peer ID across the
 * lifetime of the daemon process. /mcp reconnect → same shim presents
 * same token → daemon returns the same peer ID. No identity churn.
 *
 * Per HTTP MCP session, the daemon spins up a fresh `createSynapseServer`
 * with the resolved peer ID pre-set in the SynapseSession. bootstrapEnabled
 * is false — peer ID assignment is the daemon's job, not the tool layer's.
 *
 * Endpoints:
 *   POST /mcp          — MCP frames (Streamable HTTP transport)
 *   GET  /health       — liveness probe + connection count
 *   GET  /identity     — non-MCP shim helper: presents identityToken → peerId
 *
 * Lifecycle:
 *   - Generates port + bearer token on first start, writes daemon.json.
 *   - Logs to stderr; never exits on connection error.
 *   - Long-lived; no idle shutdown (managed externally as a service).
 */

import http from 'node:http';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { loadConfig } from './config.js';
import { buildIdentityPaths } from './types.js';
import { createSynapseServer, type SynapseSession } from './server.js';
import {
  upsertPeer, getPeer, touchPeer,
} from './storage.js';
import { generateClientId } from './identity.js';

const DEFAULT_PORT = 8765;
const HOST = '127.0.0.1';

interface DaemonState {
  port: number;
  pid: number;
  token: string;
  startedAt: string;
}

function daemonStatePath(dataDir: string): string {
  return join(dataDir, 'daemon.json');
}

function readDaemonState(dataDir: string): DaemonState | null {
  const path = daemonStatePath(dataDir);
  if (!existsSync(path)) return null;
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf-8')) as DaemonState;
    if (typeof parsed.port !== 'number' || typeof parsed.token !== 'string') return null;
    return parsed;
  } catch { return null; }
}

function writeDaemonState(dataDir: string, state: DaemonState): void {
  mkdirSync(dataDir, { recursive: true });
  writeFileSync(daemonStatePath(dataDir), JSON.stringify(state, null, 2), 'utf-8');
}

// identityToken → peerId binding. Persisted to <dataDir>/daemon-bindings.json
// so daemon restart preserves sticky identity per (label, token). Without
// persistence, every daemon restart minted a fresh peerId for each shim,
// failing the "no identity divergence" success criterion (§1.6 in the
// PR-readiness proposal). Loaded once at daemon startup, written on every
// new bind. Reads are pure in-memory.
interface IdentityBinding {
  peerId: string;
  label: string;
  // lastUsedAt is informational — supports future cleanup of long-stale
  // bindings (e.g. a label that hasn't reconnected in 30 days).
  lastUsedAt: string;
}

const identityBindings = new Map<string, IdentityBinding>();
let bindingsDataDir: string | null = null;

function bindingsPath(dataDir: string): string {
  return join(dataDir, 'daemon-bindings.json');
}

function loadIdentityBindings(dataDir: string): void {
  bindingsDataDir = dataDir;
  identityBindings.clear();
  const path = bindingsPath(dataDir);
  if (!existsSync(path)) return;
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf-8')) as Record<string, IdentityBinding>;
    for (const [token, binding] of Object.entries(parsed)) {
      if (!binding || typeof binding.peerId !== 'string' || typeof binding.label !== 'string') continue;
      identityBindings.set(token, {
        peerId: binding.peerId,
        label: binding.label,
        lastUsedAt: binding.lastUsedAt ?? new Date().toISOString(),
      });
    }
  } catch (err) {
    process.stderr.write(`synapse-daemon: failed to load daemon-bindings.json: ${(err as Error).message}\n`);
  }
}

function persistIdentityBindings(): void {
  if (!bindingsDataDir) return;
  const obj: Record<string, IdentityBinding> = {};
  for (const [token, binding] of identityBindings) obj[token] = binding;
  try {
    mkdirSync(bindingsDataDir, { recursive: true });
    writeFileSync(bindingsPath(bindingsDataDir), JSON.stringify(obj, null, 2), 'utf-8');
  } catch (err) {
    // Best-effort — never throw inside resolveIdentity. Log and continue
    // (the binding is still in-memory; next bind will retry the write).
    process.stderr.write(`synapse-daemon: failed to persist daemon-bindings.json: ${(err as Error).message}\n`);
  }
}

// Per-MCP-session transport map. Key = MCP session ID assigned by SDK.
const transports = new Map<string, StreamableHTTPServerTransport>();

function readBody(req: http.IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on('data', (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
    req.on('end', () => {
      const raw = Buffer.concat(chunks).toString('utf-8');
      if (!raw) return resolve(undefined);
      try { resolve(JSON.parse(raw)); }
      catch (err) { reject(err); }
    });
    req.on('error', reject);
  });
}

function send(res: http.ServerResponse, status: number, body: unknown): void {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}

function isInitializeRequest(body: unknown): boolean {
  if (!body || typeof body !== 'object') return false;
  // JSON-RPC: { method: "initialize", ... } or array of messages
  if (Array.isArray(body)) {
    return body.some(m => m && typeof m === 'object' && (m as { method?: string }).method === 'initialize');
  }
  return (body as { method?: string }).method === 'initialize';
}

interface ResolvedIdentity {
  peerId: string;
  label: string;
  identityToken: string;
}

// Resolve <label, identityToken> to a peer ID. Reuses existing binding
// if known; otherwise mints a new peer + persists the binding.
function resolveIdentity(
  label: string,
  identityToken: string | null,
  dataDir: string,
): ResolvedIdentity {
  const config = loadConfig({ dataDir });

  const nowIso = new Date().toISOString();

  if (identityToken) {
    const existing = identityBindings.get(identityToken);
    if (existing && existing.label === label) {
      // Refresh peer row's last_seen so cleanup doesn't reap a sticky-but-quiet client.
      const peer = getPeer(config, existing.peerId);
      if (peer) {
        touchPeer(config, existing.peerId);
      } else {
        // Peer row got cleaned up since the binding was made. Re-insert with
        // the same id so identity stays sticky across cleanup events.
        upsertPeer(config, {
          id: existing.peerId,
          label,
          registeredAt: nowIso,
          lastSeenAt: nowIso,
          capabilities: null,
        });
      }
      // Touch lastUsedAt + persist so a long-quiet binding stays fresh on
      // disk and future cleanup heuristics don't reap it.
      existing.lastUsedAt = nowIso;
      persistIdentityBindings();
      return { peerId: existing.peerId, label, identityToken };
    }
  }

  // New client OR token didn't resolve: mint fresh.
  const peerId = generateClientId(label);
  upsertPeer(config, {
    id: peerId,
    label,
    registeredAt: nowIso,
    lastSeenAt: nowIso,
    capabilities: null,
  });
  const token = identityToken ?? randomUUID();
  identityBindings.set(token, { peerId, label, lastUsedAt: nowIso });
  persistIdentityBindings();
  return { peerId, label, identityToken: token };
}

function checkAuth(req: http.IncomingMessage, expected: string): boolean {
  const header = req.headers.authorization;
  if (!header) return false;
  const expectedHeader = `Bearer ${expected}`;
  // Constant-time-ish compare (length first, then char by char). Avoids
  // exposing token-length oracle from a raw `===`.
  if (header.length !== expectedHeader.length) return false;
  let mismatch = 0;
  for (let i = 0; i < header.length; i++) {
    mismatch |= header.charCodeAt(i) ^ expectedHeader.charCodeAt(i);
  }
  return mismatch === 0;
}

async function handleMcp(
  req: http.IncomingMessage,
  res: http.ServerResponse,
  state: DaemonState,
  dataDir: string,
): Promise<void> {
  if (!checkAuth(req, state.token)) {
    send(res, 401, { error: 'unauthorized' });
    return;
  }

  let body: unknown;
  try { body = await readBody(req); }
  catch (err) {
    send(res, 400, { error: 'invalid json', detail: (err as Error).message });
    return;
  }

  const sessionId = req.headers['mcp-session-id'] as string | undefined;

  if (sessionId && transports.has(sessionId)) {
    const transport = transports.get(sessionId)!;
    await transport.handleRequest(req, res, body);
    return;
  }

  if (!isInitializeRequest(body)) {
    send(res, 400, { error: 'no session, expected initialize request' });
    return;
  }

  // New session: identify the connecting shim, mint a fresh per-connection
  // synapse server with the resolved identity pre-loaded.
  const label = (req.headers['x-synapse-label'] as string | undefined)?.trim();
  const identityToken = (req.headers['x-synapse-identity-token'] as string | undefined)?.trim() ?? null;
  if (!label) {
    send(res, 400, { error: 'missing X-Synapse-Label header' });
    return;
  }

  const identity = resolveIdentity(label, identityToken, dataDir);

  // Build a per-connection SynapseSession. bootstrapEnabled is false:
  // daemon mode never self-mints inside the tool layer.
  const session: SynapseSession = {
    selfId: identity.peerId,
    selfLabel: identity.label,
    selfSessionId: identity.peerId,
    bootstrapEnabled: false,
  };

  const mcpServer = createSynapseServer(session);
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: () => randomUUID(),
    // Plain JSON responses keep the shim a simple HTTP client. SSE
    // streams aren't needed for synapse's request/response tool surface.
    enableJsonResponse: true,
    onsessioninitialized: (id) => {
      transports.set(id, transport);
    },
  });
  transport.onclose = () => {
    if (transport.sessionId) transports.delete(transport.sessionId);
  };

  await mcpServer.connect(transport);
  // Surface identity back to the shim so it can persist the token. We
  // can't safely set headers after handleRequest writes the response,
  // so the shim is expected to call /identity separately on first run.
  await transport.handleRequest(req, res, body);
}

function handleHealth(res: http.ServerResponse): void {
  send(res, 200, {
    ok: true,
    transports: transports.size,
    bindings: identityBindings.size,
  });
}

async function handleIdentity(
  req: http.IncomingMessage,
  res: http.ServerResponse,
  state: DaemonState,
  dataDir: string,
): Promise<void> {
  if (!checkAuth(req, state.token)) {
    send(res, 401, { error: 'unauthorized' });
    return;
  }
  let body: { label?: string; identityToken?: string };
  try { body = (await readBody(req)) as typeof body ?? {}; }
  catch (err) {
    send(res, 400, { error: 'invalid json', detail: (err as Error).message });
    return;
  }
  const label = body.label?.trim();
  if (!label) {
    send(res, 400, { error: 'missing label' });
    return;
  }
  const identity = resolveIdentity(label, body.identityToken ?? null, dataDir);
  send(res, 200, {
    peerId: identity.peerId,
    identityToken: identity.identityToken,
    label: identity.label,
  });
}

export async function runDaemon(): Promise<void> {
  const config = loadConfig();
  const paths = buildIdentityPaths(config.dataDir);
  void paths;

  // §1.6 — load persisted identity bindings before accepting any traffic.
  // Without this, every daemon restart minted a new peerId per shim
  // despite the shim's identity-token file persisting — failing the "no
  // identity divergence" success criterion.
  loadIdentityBindings(config.dataDir);

  // Reuse existing token if a previous daemon wrote one — clients that
  // saved it are still valid. New token only when daemon.json is absent.
  const existing = readDaemonState(config.dataDir);
  const port = parseInt(process.env.SYNAPSE_DAEMON_PORT ?? `${DEFAULT_PORT}`, 10);
  const token = existing?.token ?? randomBytes(24).toString('hex');

  const httpServer = http.createServer(async (req, res) => {
    try {
      if (req.method === 'POST' && req.url === '/mcp') {
        await handleMcp(req, res, { ...(existing ?? {}), port, pid: process.pid, token, startedAt: new Date().toISOString() }, config.dataDir);
        return;
      }
      if (req.method === 'POST' && req.url === '/identity') {
        await handleIdentity(req, res, { ...(existing ?? {}), port, pid: process.pid, token, startedAt: new Date().toISOString() }, config.dataDir);
        return;
      }
      if (req.method === 'GET' && req.url === '/health') {
        handleHealth(res);
        return;
      }
      send(res, 404, { error: 'not found' });
    } catch (err) {
      process.stderr.write(`synapse-daemon: ${(err as Error).stack ?? err}\n`);
      if (!res.headersSent) send(res, 500, { error: 'internal' });
    }
  });

  httpServer.on('error', (err) => {
    process.stderr.write(`synapse-daemon listen: ${(err as Error).stack ?? err}\n`);
    process.exit(1);
  });

  httpServer.listen(port, HOST, () => {
    const state: DaemonState = {
      port,
      pid: process.pid,
      token,
      startedAt: new Date().toISOString(),
    };
    writeDaemonState(config.dataDir, state);
    process.stderr.write(`synapse-daemon listening on http://${HOST}:${port} (pid ${process.pid})\n`);
  });

  // Graceful shutdown
  const shutdown = (sig: string) => {
    process.stderr.write(`synapse-daemon received ${sig}, exiting\n`);
    httpServer.close(() => process.exit(0));
    setTimeout(() => process.exit(1), 5000).unref();
  };
  process.on('SIGINT', () => shutdown('SIGINT'));
  process.on('SIGTERM', () => shutdown('SIGTERM'));
}
