/**
 * Synapse daemon — single long-lived MCP server, multi-client.
 *
 * Each connecting shim presents:
 *   - Authorization: Bearer <token>           (auth, from ~/.claude/synapse/daemon.json)
 *   - X-Synapse-Label: <label>                (identifies client class — code/desktop/etc)
 *   - X-Synapse-Identity-Token: <client-uuid> (sticky identity, generated by the shim)
 *
 * The daemon binds <label, identityToken> to a single peer ID across the
 * lifetime of the daemon process. /mcp reconnect → same shim presents
 * same token → daemon returns the same peer ID. No identity churn.
 *
 * Per HTTP MCP session, the daemon spins up a fresh `createSynapseServer`
 * with the resolved peer ID pre-set in the SynapseSession. bootstrapEnabled
 * is false — peer ID assignment is the daemon's job, not the tool layer's.
 *
 * Endpoints:
 *   POST /mcp          — MCP frames (Streamable HTTP transport)
 *   GET  /health       — liveness probe + connection count
 *   GET  /identity     — non-MCP shim helper: presents identityToken → peerId
 *
 * Lifecycle:
 *   - Generates port + bearer token on first start, writes daemon.json.
 *   - Logs to stderr; never exits on connection error.
 *   - Long-lived; no idle shutdown (managed externally as a service).
 */

import http from 'node:http';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, existsSync, renameSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { loadConfig } from './config.js';
import { buildIdentityPaths } from './types.js';
import { createSynapseServer, type SynapseSession } from './server.js';
import {
  upsertPeer, getPeer, touchPeer,
  clearAllPeerBusyState, pruneStaleBusyState,
  pruneStaleIdleLog,
  expireRecruits, insertMessage,
  listThreadParticipants,
  writePeerAlias, logAudit,
  type RecruitRow,
} from './storage.js';
import type { Message, SynapseConfig } from './types.js';

// §4.10 — synthetic [RECRUIT_EXPIRED] message emitted when a recruit
// elapses its TTL without being fulfilled. Lands in the originator's
// inbox so they know the call for help didn't land. fromId is a marker
// constant 'daemon-system' which intentionally doesn't match any peer
// row; pollInbox tolerates missing peer rows via LEFT JOIN.
function emitRecruitExpiredMessage(config: SynapseConfig, recruit: RecruitRow): void {
  const participants = listThreadParticipants(config, recruit.threadId);
  // Exclude originator from the joined count.
  const joinedCount = Math.max(0, participants.filter(p => p.peerId !== recruit.originatorId).length);
  const now = new Date().toISOString();
  const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
  const body = `[RECRUIT_EXPIRED] id=${recruit.id} joined=${joinedCount}\n\nRecruit "${recruit.description.slice(0, 80)}${recruit.description.length > 80 ? '…' : ''}" expired after ${recruit.urgency} TTL with ${joinedCount === 0 ? 'no' : joinedCount} prospect${joinedCount === 1 ? '' : 's'} joined.`;
  const msg: Message = {
    id: randomUUID(),
    fromId: 'daemon-system',
    toId: recruit.originatorId,
    threadId: recruit.threadId,
    parentId: null,
    body,
    workspace: recruit.workspace,
    createdAt: now,
    expiresAt,
    readAt: null,
  };
  insertMessage(config, msg);
}
import { generateClientId } from './identity.js';
import { inc as bumpCounter } from './counters.js';

const DEFAULT_PORT = 8765;
const HOST = '127.0.0.1';

interface DaemonState {
  port: number;
  pid: number;
  token: string;
  startedAt: string;
}

function daemonStatePath(dataDir: string): string {
  return join(dataDir, 'daemon.json');
}

function readDaemonState(dataDir: string): DaemonState | null {
  const path = daemonStatePath(dataDir);
  if (!existsSync(path)) return null;
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf-8')) as DaemonState;
    if (typeof parsed.port !== 'number' || typeof parsed.token !== 'string') return null;
    return parsed;
  } catch { return null; }
}

function writeDaemonState(dataDir: string, state: DaemonState): void {
  mkdirSync(dataDir, { recursive: true });
  writeFileSync(daemonStatePath(dataDir), JSON.stringify(state, null, 2), 'utf-8');
}

// identityToken → peerId binding. Persisted to <dataDir>/daemon-bindings.json
// so daemon restart preserves sticky identity per (label, token). Without
// persistence, every daemon restart minted a fresh peerId for each shim,
// failing the "no identity divergence" success criterion (§1.6 in the
// PR-readiness proposal). Loaded once at daemon startup, written on every
// new bind. Reads are pure in-memory.
interface IdentityBinding {
  peerId: string;
  label: string;
  // lastUsedAt is informational — supports future cleanup of long-stale
  // bindings (e.g. a label that hasn't reconnected in 30 days).
  lastUsedAt: string;
  // §1.11 — sessionFingerprint distinguishes "same shim reconnecting"
  // from "different shim claiming a token already in active use."
  // Same fingerprint on a re-bind is a benign reconnect (shim crashed
  // or /mcp reconnected); different fingerprint while the existing
  // binding is fresh is a contention bug we want to refuse loudly.
  // Optional for backward compat — bindings minted by pre-§1.11 daemon
  // load with this unset; first new bind under that token records the
  // fingerprint and locks the slot from then on.
  sessionFingerprint?: string;
}

// §1.11 — staleness window for evicting a binding owned by a different
// fingerprint. If the existing binding hasn't been refreshed in this
// window, the old shim is presumed dead and the new fingerprint can
// take over the slot without an error.
const FINGERPRINT_EVICTION_MS = 10 * 60 * 1000; // 10 min

const identityBindings = new Map<string, IdentityBinding>();
let bindingsDataDir: string | null = null;

function bindingsPath(dataDir: string): string {
  return join(dataDir, 'daemon-bindings.json');
}

function loadIdentityBindings(dataDir: string): void {
  bindingsDataDir = dataDir;
  identityBindings.clear();
  const path = bindingsPath(dataDir);
  if (!existsSync(path)) {
    process.stderr.write(`synapse-daemon: identityBindings.loaded count=0 (no file)\n`);
    return;
  }
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf-8')) as Record<string, IdentityBinding>;
    for (const [token, binding] of Object.entries(parsed)) {
      if (!binding || typeof binding.peerId !== 'string' || typeof binding.label !== 'string') continue;
      identityBindings.set(token, {
        peerId: binding.peerId,
        label: binding.label,
        lastUsedAt: binding.lastUsedAt ?? new Date().toISOString(),
        sessionFingerprint: typeof binding.sessionFingerprint === 'string'
          ? binding.sessionFingerprint
          : undefined,
      });
    }
    process.stderr.write(`synapse-daemon: identityBindings.loaded count=${identityBindings.size}\n`);
    bumpCounter('identityBindings.loaded_count', identityBindings.size);
  } catch (err) {
    // Degraded mode — start with empty Map and continue serving. Every
    // shim mints a fresh peerId until the next successful write. This
    // is the SAME behavior as before §1.6 shipped, so worst-case
    // regression is "back to v6.0 identity churn until file is rewritten."
    process.stderr.write(`synapse-daemon: identityBindings.fallback_to_memory reason=${(err as Error).message}\n`);
    bumpCounter('identityBindings.parse_failures');
    bumpCounter('identityBindings.fallback_to_memory');
    identityBindings.clear();
  }
}

// Debounced flush — concurrent binds within FLUSH_DEBOUNCE_MS coalesce
// into a single disk write. Last-write-wins semantics (binds are
// idempotent at the token level, so a coalesced flush represents the
// merged state correctly).
const FLUSH_DEBOUNCE_MS = 200;
let flushTimer: NodeJS.Timeout | null = null;

function persistIdentityBindings(): void {
  if (!bindingsDataDir) return;
  if (flushTimer) clearTimeout(flushTimer);
  flushTimer = setTimeout(() => {
    flushTimer = null;
    flushIdentityBindingsSync();
  }, FLUSH_DEBOUNCE_MS);
  flushTimer.unref?.();
}

// Synchronous flush — used by the debounced timer AND by exit handlers
// so a daemon shutdown after a recent bind doesn't drop the write.
// Atomic: writes to a .tmp sibling and renames into place. renameSync is
// atomic on POSIX (same filesystem) and on Windows when src+dst are on
// the same volume — both true here since both paths live in dataDir.
// Callers from process exit hooks pre-clear flushTimer so the debounced
// version doesn't double-write the same state.
function flushIdentityBindingsSync(): void {
  if (!bindingsDataDir) return;
  const obj: Record<string, IdentityBinding> = {};
  for (const [token, binding] of identityBindings) obj[token] = binding;
  const finalPath = bindingsPath(bindingsDataDir);
  const tmpPath = `${finalPath}.tmp`;
  try {
    mkdirSync(bindingsDataDir, { recursive: true });
    writeFileSync(tmpPath, JSON.stringify(obj, null, 2), 'utf-8');
    renameSync(tmpPath, finalPath);
    bumpCounter('identityBindings.writes');
  } catch (err) {
    process.stderr.write(`synapse-daemon: identityBindings.write_failed: ${(err as Error).message}\n`);
    bumpCounter('identityBindings.write_failures');
    // Best-effort cleanup of the orphan .tmp so the next attempt has a
    // clean slate. Never throw — the in-memory map is still authoritative.
    try { if (existsSync(tmpPath)) unlinkSync(tmpPath); }
    catch { /* nothing to do */ }
  }
}

// Called from exit handlers (signal handlers + process.on('exit')) so a
// pending debounced write isn't dropped. Synchronous; safe to call from
// the synchronous 'exit' event handler. Idempotent.
function flushPendingBindingsBeforeExit(): void {
  if (flushTimer) {
    clearTimeout(flushTimer);
    flushTimer = null;
  }
  flushIdentityBindingsSync();
}

// Per-MCP-session transport map. Key = MCP session ID assigned by SDK.
const transports = new Map<string, StreamableHTTPServerTransport>();

function readBody(req: http.IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on('data', (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
    req.on('end', () => {
      const raw = Buffer.concat(chunks).toString('utf-8');
      if (!raw) return resolve(undefined);
      try { resolve(JSON.parse(raw)); }
      catch (err) { reject(err); }
    });
    req.on('error', reject);
  });
}

function send(res: http.ServerResponse, status: number, body: unknown): void {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}

function isInitializeRequest(body: unknown): boolean {
  if (!body || typeof body !== 'object') return false;
  // JSON-RPC: { method: "initialize", ... } or array of messages
  if (Array.isArray(body)) {
    return body.some(m => m && typeof m === 'object' && (m as { method?: string }).method === 'initialize');
  }
  return (body as { method?: string }).method === 'initialize';
}

interface ResolvedIdentity {
  peerId: string;
  label: string;
  identityToken: string;
}

// §1.11 — error class for HTTP layer to translate into 409 / clear
// reason text. Distinguishable from generic Error via instanceof.
class FingerprintConflictError extends Error {
  constructor(
    public readonly token: string,
    public readonly existingFingerprint: string,
    public readonly existingPeerId: string,
    public readonly incomingFingerprint: string,
  ) {
    super(
      `INVALID_SESSION_FINGERPRINT: token already actively bound to a different shim ` +
      `(existing fingerprint ${existingFingerprint.slice(0, 8)}…, incoming ${incomingFingerprint.slice(0, 8)}…). ` +
      `If you are the original shim, reuse the existing identity-token file. ` +
      `If you are a fresh shim, mint a new identity-token (delete <label>-identity.json). ` +
      `If the original is dead, wait ${Math.ceil(FINGERPRINT_EVICTION_MS / 60_000)} minutes for the binding to age out.`,
    );
    this.name = 'FingerprintConflictError';
  }
}

// Resolve <label, identityToken, sessionFingerprint> to a peer ID. Reuses
// existing binding if known and fingerprint matches; otherwise mints a
// new peer + persists the binding.
//
// §1.11 fingerprint contention rules:
//   - existing binding + same fingerprint → ALLOW (benign reconnect)
//   - existing binding + different fingerprint + lastUsedAt < 10min → REJECT
//   - existing binding + different fingerprint + lastUsedAt ≥ 10min → ALLOW (eviction)
//   - existing binding + no fingerprint recorded (legacy) → ALLOW + adopt incoming fingerprint
//   - no existing binding → mint, record fingerprint
function resolveIdentity(
  label: string,
  identityToken: string | null,
  dataDir: string,
  sessionFingerprint: string | null = null,
): ResolvedIdentity {
  const config = loadConfig({ dataDir });

  const nowIso = new Date().toISOString();
  const nowMs = Date.now();

  if (identityToken) {
    const existing = identityBindings.get(identityToken);
    if (existing && existing.label === label) {
      // §1.11 fingerprint check.
      if (sessionFingerprint && existing.sessionFingerprint) {
        if (existing.sessionFingerprint !== sessionFingerprint) {
          const lastUsedMs = new Date(existing.lastUsedAt).getTime();
          const ageMs = nowMs - lastUsedMs;
          if (ageMs < FINGERPRINT_EVICTION_MS) {
            // Different fingerprint, binding still fresh — refuse.
            bumpCounter('identityBindings.fingerprint_rejects');
            throw new FingerprintConflictError(
              identityToken,
              existing.sessionFingerprint,
              existing.peerId,
              sessionFingerprint,
            );
          }
          // Different fingerprint AND binding stale — eviction path.
          bumpCounter('identityBindings.fingerprint_evictions');
          existing.sessionFingerprint = sessionFingerprint;
        }
      } else if (sessionFingerprint && !existing.sessionFingerprint) {
        // Legacy binding (pre-§1.11 daemon write) gets stamped with the
        // first incoming fingerprint. From then on it's locked.
        existing.sessionFingerprint = sessionFingerprint;
      }

      // Refresh peer row's last_seen so cleanup doesn't reap a sticky-but-quiet client.
      const peer = getPeer(config, existing.peerId);
      if (peer) {
        touchPeer(config, existing.peerId);
      } else {
        upsertPeer(config, {
          id: existing.peerId,
          label,
          registeredAt: nowIso,
          lastSeenAt: nowIso,
          capabilities: null,
        });
      }
      existing.lastUsedAt = nowIso;
      persistIdentityBindings();
      return { peerId: existing.peerId, label, identityToken };
    }
  }

  // New client OR token didn't resolve: mint fresh.
  const peerId = generateClientId(label);
  upsertPeer(config, {
    id: peerId,
    label,
    registeredAt: nowIso,
    lastSeenAt: nowIso,
    capabilities: null,
  });
  const token = identityToken ?? randomUUID();
  identityBindings.set(token, {
    peerId,
    label,
    lastUsedAt: nowIso,
    sessionFingerprint: sessionFingerprint ?? undefined,
  });
  persistIdentityBindings();
  return { peerId, label, identityToken: token };
}

function checkAuth(req: http.IncomingMessage, expected: string): boolean {
  const header = req.headers.authorization;
  if (!header) return false;
  const expectedHeader = `Bearer ${expected}`;
  // Constant-time-ish compare (length first, then char by char). Avoids
  // exposing token-length oracle from a raw `===`.
  if (header.length !== expectedHeader.length) return false;
  let mismatch = 0;
  for (let i = 0; i < header.length; i++) {
    mismatch |= header.charCodeAt(i) ^ expectedHeader.charCodeAt(i);
  }
  return mismatch === 0;
}

async function handleMcp(
  req: http.IncomingMessage,
  res: http.ServerResponse,
  state: DaemonState,
  dataDir: string,
): Promise<void> {
  if (!checkAuth(req, state.token)) {
    send(res, 401, { error: 'unauthorized' });
    return;
  }

  let body: unknown;
  try { body = await readBody(req); }
  catch (err) {
    send(res, 400, { error: 'invalid json', detail: (err as Error).message });
    return;
  }

  const sessionId = req.headers['mcp-session-id'] as string | undefined;

  if (sessionId && transports.has(sessionId)) {
    const transport = transports.get(sessionId)!;
    await transport.handleRequest(req, res, body);
    return;
  }

  if (!isInitializeRequest(body)) {
    send(res, 400, { error: 'no session, expected initialize request' });
    return;
  }

  // New session: identify the connecting shim, mint a fresh per-connection
  // synapse server with the resolved identity pre-loaded.
  const label = (req.headers['x-synapse-label'] as string | undefined)?.trim();
  const identityToken = (req.headers['x-synapse-identity-token'] as string | undefined)?.trim() ?? null;
  const sessionFingerprint = (req.headers['x-synapse-session-fingerprint'] as string | undefined)?.trim() ?? null;
  if (!label) {
    send(res, 400, { error: 'missing X-Synapse-Label header' });
    return;
  }

  let identity: ResolvedIdentity;
  try {
    identity = resolveIdentity(label, identityToken, dataDir, sessionFingerprint);
  } catch (err) {
    if (err instanceof FingerprintConflictError) {
      send(res, 409, { error: 'INVALID_SESSION_FINGERPRINT', detail: err.message });
      return;
    }
    throw err;
  }

  // Build a per-connection SynapseSession. bootstrapEnabled is false:
  // daemon mode never self-mints inside the tool layer.
  const session: SynapseSession = {
    selfId: identity.peerId,
    selfLabel: identity.label,
    selfSessionId: identity.peerId,
    bootstrapEnabled: false,
  };

  const mcpServer = createSynapseServer(session);
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: () => randomUUID(),
    // Plain JSON responses keep the shim a simple HTTP client. SSE
    // streams aren't needed for synapse's request/response tool surface.
    enableJsonResponse: true,
    onsessioninitialized: (id) => {
      transports.set(id, transport);
    },
  });
  transport.onclose = () => {
    if (transport.sessionId) transports.delete(transport.sessionId);
  };

  await mcpServer.connect(transport);
  // Surface identity back to the shim so it can persist the token. We
  // can't safely set headers after handleRequest writes the response,
  // so the shim is expected to call /identity separately on first run.
  await transport.handleRequest(req, res, body);
}

function handleHealth(res: http.ServerResponse): void {
  send(res, 200, {
    ok: true,
    transports: transports.size,
    bindings: identityBindings.size,
  });
}

// §1.6(c) — heartbeat staleness threshold above which a priorPeerId is
// considered "cold" (process exited, identity rotated). Anything below
// this is a warm contention case that §1.11 already handles. Tunable
// via env so tests can shorten the window without waiting in real time.
const COLD_RESTART_STALE_SEC = Number.parseInt(
  process.env.SYNAPSE_COLD_RESTART_STALE_SEC ?? '600',
  10,
);

async function handleIdentity(
  req: http.IncomingMessage,
  res: http.ServerResponse,
  state: DaemonState,
  dataDir: string,
): Promise<void> {
  if (!checkAuth(req, state.token)) {
    send(res, 401, { error: 'unauthorized' });
    return;
  }
  let body: {
    label?: string;
    identityToken?: string;
    sessionFingerprint?: string;
    priorPeerId?: string;
  };
  try { body = (await readBody(req)) as typeof body ?? {}; }
  catch (err) {
    send(res, 400, { error: 'invalid json', detail: (err as Error).message });
    return;
  }
  const label = body.label?.trim();
  if (!label) {
    send(res, 400, { error: 'missing label' });
    return;
  }
  const sessionFingerprint = typeof body.sessionFingerprint === 'string'
    ? body.sessionFingerprint.trim()
    : null;
  const priorPeerId = typeof body.priorPeerId === 'string'
    ? body.priorPeerId.trim()
    : null;
  let identity: ResolvedIdentity;
  try {
    identity = resolveIdentity(label, body.identityToken ?? null, dataDir, sessionFingerprint);
  } catch (err) {
    if (err instanceof FingerprintConflictError) {
      send(res, 409, { error: 'INVALID_SESSION_FINGERPRINT', detail: err.message });
      return;
    }
    throw err;
  }

  // §1.6(c) cold-restart aliasing — when the shim-side identity file
  // remembered a peerId that's now different from the freshly-resolved
  // one, this is a peerId rotation across a process boundary (NOT a
  // warm §1.11 contention rebind, which keeps the same peerId via the
  // identity-token path). Register the alias so messages still in flight
  // to the old id route to the new one. Only when the prior is truly
  // gone (heartbeat older than the cold-restart threshold) — a fresh
  // prior heartbeat means another shim is alive on it; that's a §1.11
  // contention case, not a cold rotation.
  let aliasRegistered = false;
  if (priorPeerId && priorPeerId !== identity.peerId) {
    try {
      const config = loadConfig({ dataDir });
      const prior = getPeer(config, priorPeerId);
      if (prior) {
        const lastSeenMs = new Date(prior.lastSeenAt).getTime();
        const ageSec = Math.max(0, Math.floor((Date.now() - lastSeenMs) / 1000));
        if (ageSec >= COLD_RESTART_STALE_SEC) {
          writePeerAlias(config, priorPeerId, identity.peerId);
          aliasRegistered = true;
          bumpCounter('identityBindings.cold_alias_writes');
          try {
            logAudit(config, {
              id: randomUUID(),
              toolName: 'peer_cold_alias',
              callerId: identity.peerId,
              threadId: null,
              originThreadId: null,
              originMessageId: null,
              argsHash: '',
              result: 'allowed',
              reason: `from=${priorPeerId} to=${identity.peerId} lastSeenAgeSec=${ageSec}`,
              calledAt: new Date().toISOString(),
            });
          } catch { /* best-effort — never fail /identity for audit */ }
        }
        // else: prior is fresh → §1.11 contention case, no alias.
      }
      // else: prior peer doesn't exist (fresh dataDir or pruned) — silently skip.
    } catch (err) {
      process.stderr.write(`synapse-daemon: cold-alias write failed: ${(err as Error).message}\n`);
    }
  }

  send(res, 200, {
    peerId: identity.peerId,
    identityToken: identity.identityToken,
    label: identity.label,
    ...(aliasRegistered ? { coldAliasRegistered: { from: priorPeerId, to: identity.peerId } } : {}),
  });
}

export async function runDaemon(): Promise<void> {
  const config = loadConfig();
  const paths = buildIdentityPaths(config.dataDir);
  void paths;

  // §1.6 — load persisted identity bindings before accepting any traffic.
  // Without this, every daemon restart minted a new peerId per shim
  // despite the shim's identity-token file persisting — failing the "no
  // identity divergence" success criterion.
  loadIdentityBindings(config.dataDir);

  // §4.10 — daemon-restart busy-state sweep. Concurrent-binding restarts
  // shouldn't leak stale "busy" entries (the peer that owned the busy row
  // is gone with the prior daemon's in-memory state). Per the agreed
  // contract: daemon restart = everyone idle.
  try {
    const cleared = clearAllPeerBusyState(config);
    if (cleared > 0) {
      bumpCounter('busy.startup_swept');
      process.stderr.write(`synapse-daemon: cleared ${cleared} stale peer_busy_state row(s) on startup\n`);
    }
  } catch (err) {
    process.stderr.write(`synapse-daemon: busy-state sweep failed: ${(err as Error).message}\n`);
  }

  // §4.10 — periodic GC for busy-state staleness + recruit expiry.
  // Stale-busy: peers in busy >30min auto-clear (configurable via
  // SYNAPSE_BUSY_STALE_SEC). Expired recruits: TTL elapsed without
  // fulfillment → emit synthetic [RECRUIT_EXPIRED] message back to
  // originator's inbox so they know the recruit didn't land. Both run
  // on a single 60s timer (cheap SQL ops, no need to split).
  const RECRUIT_GC_INTERVAL_MS = 60_000;
  const recruitGcTimer = setInterval(() => {
    try {
      const stalePruned = pruneStaleBusyState(config);
      if (stalePruned > 0) bumpCounter('busy.stale_clears');
    } catch (err) {
      process.stderr.write(`synapse-daemon: stale-busy GC failed: ${(err as Error).message}\n`);
    }
    try {
      const idlePruned = pruneStaleIdleLog(config);
      if (idlePruned > 0) bumpCounter('busy.idle_log_pruned');
    } catch (err) {
      process.stderr.write(`synapse-daemon: idle-log GC failed: ${(err as Error).message}\n`);
    }
    try {
      const expired = expireRecruits(config);
      for (const r of expired) {
        emitRecruitExpiredMessage(config, r);
        bumpCounter('recruit.expired');
      }
    } catch (err) {
      process.stderr.write(`synapse-daemon: recruit-expiry GC failed: ${(err as Error).message}\n`);
    }
  }, RECRUIT_GC_INTERVAL_MS);
  recruitGcTimer.unref?.();

  // Reuse existing token if a previous daemon wrote one — clients that
  // saved it are still valid. New token only when daemon.json is absent.
  const existing = readDaemonState(config.dataDir);
  const port = parseInt(process.env.SYNAPSE_DAEMON_PORT ?? `${DEFAULT_PORT}`, 10);
  const token = existing?.token ?? randomBytes(24).toString('hex');

  const httpServer = http.createServer(async (req, res) => {
    try {
      if (req.method === 'POST' && req.url === '/mcp') {
        await handleMcp(req, res, { ...(existing ?? {}), port, pid: process.pid, token, startedAt: new Date().toISOString() }, config.dataDir);
        return;
      }
      if (req.method === 'POST' && req.url === '/identity') {
        await handleIdentity(req, res, { ...(existing ?? {}), port, pid: process.pid, token, startedAt: new Date().toISOString() }, config.dataDir);
        return;
      }
      if (req.method === 'GET' && req.url === '/health') {
        handleHealth(res);
        return;
      }
      send(res, 404, { error: 'not found' });
    } catch (err) {
      process.stderr.write(`synapse-daemon: ${(err as Error).stack ?? err}\n`);
      if (!res.headersSent) send(res, 500, { error: 'internal' });
    }
  });

  httpServer.on('error', (err) => {
    process.stderr.write(`synapse-daemon listen: ${(err as Error).stack ?? err}\n`);
    process.exit(1);
  });

  // §1.5(b) — TCP keepalive on every incoming connection. Long-poll
  // wait_reply requests can sit idle for up to 300s waiting for a peer
  // reply; without keepalive packets at the OS layer, NAT / proxy /
  // firewall idle timers tear down the connection silently and the
  // shim sees "Connection closed" mid-poll. Setting keepAlive on the
  // raw socket emits TCP-level probes every 30s, holding the path
  // open across idle periods. setTimeout(0) disables Node's per-socket
  // idle timeout for the same reason.
  httpServer.on('connection', (socket) => {
    try {
      socket.setKeepAlive(true, 30_000);
      socket.setTimeout(0);
    } catch {
      // best-effort; never crash the connection handler
    }
  });
  // Tune Node http server timeouts so a long-running response (e.g.
  // 300s wait_reply) isn't killed by the default 5min header-keepalive
  // ceiling. headersTimeout must be > requestTimeout per Node docs.
  httpServer.keepAliveTimeout = 310_000;
  httpServer.headersTimeout = 320_000;
  httpServer.requestTimeout = 0;

  httpServer.listen(port, HOST, () => {
    const state: DaemonState = {
      port,
      pid: process.pid,
      token,
      startedAt: new Date().toISOString(),
    };
    writeDaemonState(config.dataDir, state);
    process.stderr.write(`synapse-daemon listening on http://${HOST}:${port} (pid ${process.pid})\n`);
  });

  // Graceful shutdown — flush any pending debounced bindings BEFORE the
  // server-close callback fires so a SIGTERM right after a bind doesn't
  // lose the write. flushPendingBindingsBeforeExit is synchronous + idempotent.
  const shutdown = (sig: string) => {
    process.stderr.write(`synapse-daemon received ${sig}, exiting\n`);
    flushPendingBindingsBeforeExit();
    httpServer.close(() => process.exit(0));
    setTimeout(() => process.exit(1), 5000).unref();
  };
  process.on('SIGINT', () => shutdown('SIGINT'));
  process.on('SIGTERM', () => shutdown('SIGTERM'));

  // Catches synapse_request_restart's process.exit(0) and any other
  // non-signal exit path (e.g. uncaughtException → exit). 'exit' fires
  // synchronously and is the last hook before the process dies, so
  // flushPendingBindingsBeforeExit gets one more chance to land state.
  process.on('exit', () => {
    flushPendingBindingsBeforeExit();
  });
}
